In [2]:
import pandas as pd

df = pd.read_csv("Retail_dataset.csv")

In [6]:
#Q1

data = {
    "Product": ["Laptop", "Mobile", "Tablet", "Keyboard", "Mouse"],
    "Region": ["North", "South", "East", "West", "North"],
    "Sales": [1200, 900, 750, 400, 300],
    "Quantity": [3, 5, 2, 8, 10]
}
df1 = pd.DataFrame(data)
df1

    Product Region  Sales  Quantity
0    Laptop  North   1200         3
1    Mobile  South    900         5
2    Tablet   East    750         2
3  Keyboard   West    400         8
4     Mouse  North    300        10

In [8]:
#Q2

df.head()      # pehle 5 rows
df.tail()      # aakhri 5 rows
df.info()      # structure
df.shape       # (rows, columns)


from IPython.display import display
display(df.head())
display(df.tail())
df.info()
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     object
 2   Product   90 non-null     object
 3   Region    90 non-null     object
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.3+ KB

   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4

    Order_ID Customer   Product Region  Sales  Quantity
85      1086    Pooja    Laptop   East   1330         2
86      1087    Anita  Keyboard   West    741         3
87      1088    Karan   Monitor   East    875         2
88      1089      Raj    Tablet  North   2213         5
89      1090    Priya    Laptop  South   1270         2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     object
 2   Product   90 non-null     object
 3   Region    90 non-null     object
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.3+ KB
(90, 6)

In [9]:
#Q3

df[["Product", "Region", "Sales"]]

     Product Region  Sales
0     Laptop   West   1056
1     Tablet  South    904
2     Laptop  South   1597
3   Keyboard  North    777
4      Phone  South   2028
..       ...    ...    ...
85    Laptop   East   1330
86  Keyboard   West    741
87   Monitor   East    875
88    Tablet  North   2213
89    Laptop  South   1270

[90 rows x 3 columns]

In [10]:
#Q4

df.loc[10]              # index 10 wali row
df.loc[20, "Sales"]     # index 20 ki Sales value

np.int64(1021)

In [11]:
#Q5

df.iloc[0:6, 0:4]       # first 6 rows, first 4 columns
df.iloc[2]["Sales"]     # 3rd row ki Sales value (index 2)

np.int64(1597)

In [12]:
#Q6

df.iloc[0:10]     # pehle 10 rows
df.iloc[15:26]    # rows 15 se 25 (26 exclude, 25 include)

    Order_ID Customer  Product Region  Sales  Quantity
15      1016    Karan  Monitor   West    796         3
16      1017     Neha   Laptop   East   2015         2
17      1018    Anita    Phone  North   1637         3
18      1019     Amit    Phone   East    748         7
19      1020     Neha   Laptop   West   1503         6
20      1021    Priya   Laptop  North   1021         4
21      1022      Raj   Tablet  South    886         7
22      1023    Rahul   Laptop  South   2267         3
23      1024    Karan  Monitor   East    814         7
24      1025    Meera  Monitor   West   1926         6
25      1026    Anita   Tablet   East    839         5

In [13]:
#7

df[df["Region"] == "East"]
df[df["Sales"] > 1500]

    Order_ID Customer   Product Region  Sales  Quantity
2       1003    Meera    Laptop  South   1597         5
4       1005    Priya     Phone  South   2028         4
9       1010     Amit     Phone   West   1998         4
10      1011      Raj   Monitor  North   1693         6
13      1014    Rohan     Phone  South   2078         3
16      1017     Neha    Laptop   East   2015         2
17      1018    Anita     Phone  North   1637         3
19      1020     Neha    Laptop   West   1503         6
22      1023    Rahul    Laptop  South   2267         3
24      1025    Meera   Monitor   West   1926         6
26      1027    Vikas    Laptop  North   1864         8
27      1028    Vikas    Laptop  North   1551         3
29      1030    Rohan   Monitor   West   1932         5
31      1032     Amit    Laptop   East   2226         6
34      1035     Amit    Tablet   East   2104         3
35      1036    Rohan     Phone   East   2136         8
36      1037      Raj     Phone   East   1650         4
37      1038     Amit   Monitor   East   1567         8
38      1039    Meera  Keyboard   East   2455         3
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
44      1045    Priya     Phone   East   1875         4
49      1050    Karan   Monitor   West   2034         7
52      1053    Rahul    Laptop   East   2276         1
57      1058    Meera    Tablet  North   1666         8
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
60      1061    Vikas   Monitor  South   1837         8
61      1062    Meera  Keyboard  North   1688         4
63      1064    Pooja  Keyboard   West   2310         5
66      1067    Rahul    Tablet   East   1875         6
69      1070    Rahul    Tablet   West   2134         5
71      1072    Anita  Keyboard   East   1702         3
74      1075     Amit   Monitor  North   2390         5
79      1080    Pooja    Tablet   East   1829         2
81      1082    Anita     Phone   East   1695         7
82      1083     Neha  Keyboard   East   2034         5
88      1089      Raj    Tablet  North   2213         5

In [14]:
#Q8

df[(df["Region"] == "West") & (df["Sales"] > 1200)]

    Order_ID Customer   Product Region  Sales  Quantity
9       1010     Amit     Phone   West   1998         4
19      1020     Neha    Laptop   West   1503         6
24      1025    Meera   Monitor   West   1926         6
29      1030    Rohan   Monitor   West   1932         5
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
49      1050    Karan   Monitor   West   2034         7
55      1056    Rahul    Laptop   West   1481         1
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
63      1064    Pooja  Keyboard   West   2310         5
68      1069    Priya    Laptop   West   1422         6
69      1070    Rahul    Tablet   West   2134         5
73      1074    Meera  Keyboard   West   1429         7
83      1084    Rohan    Laptop   West   1204         5
84      1085     Neha   Monitor   West   1339         7

In [15]:
#Q9

df.describe()

          Order_ID        Sales   Quantity
count    90.000000    90.000000  90.000000
mean   1045.500000  1406.888889   4.700000
std      26.124701   531.748302   2.179836
min    1001.000000   515.000000   1.000000
25%    1023.250000   890.500000   3.000000
50%    1045.500000  1402.000000   5.000000
75%    1067.750000  1857.250000   7.000000
max    1090.000000  2455.000000   8.000000

In [16]:
#Q10

print("Total Sales:", df["Sales"].sum())
print("Average Sales:", df["Sales"].mean())
print("Maximum Sales:", df["Sales"].max())
print("Minimum Sales:", df["Sales"].min())

Total Sales: 126620
Average Sales: 1406.888888888889
Maximum Sales: 2455
Minimum Sales: 515